version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: rubocop-performance
    versions:
    - 1.10.0
    - 1.10.1
    - 1.10.2
    - 1.9.2
  - dependency-name: regexp_parser
    versions:
    - 2.0.3
  - dependency-name: rubocop-rspec
    versions:
    - 2.1.0
